### ISSUE TITLE
Wrong layout name referenced in Media Streaming of ExoPlayer - Customizing the user interface

### ISSUE THREAD

**Issue by anthonymonori** [googlecodelabs/exoplayer-intro#7] opened 2017-08-17 06:23 UTC
Under the section: **Customizing the appearance of PlaybackControlView**

The user is instructed to create a new layout file named: `custom_playback_control.xml`

And later the following code-block is shown to reference the layout on the `SimpleExoPlayerView`:

```java
<com.google.android.exoplayer2.ui.SimpleExoPlayerView android:id="@+id/video_view"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   app:controller_layout_id="@layout/custom_playback_control_view"/>
```

Please note that `custom_playback_control_view` is referenced but that does not exist

**Comment by marcbaechinger** [comment] 2018-01-05 16:17
Thanks for reporting. 

The problem is fixed in the codelab template and will be available as soon as the updated codelab is pushed to production.

Many thanks!

**Closed by marcbaechinger** 2018-01-05 16:17 UTC
